services: 
    backend:
        image: helen24/quirknotes_backend:latest 
        ports:
            - "4000:4000" 
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest 
        ports:
            - "27017:27017"
